#!/bin/bash

wget -nc http://storage.googleapis.com/books/ngrams/books/googlebooks-eng-all-1gram-20120701-0.gz
wget -nc http://storage.googleapis.com/books/ngrams/books/googlebooks-eng-all-1gram-20120701-1.gz
wget -nc http://storage.googleapis.com/books/ngrams/books/googlebooks-eng-all-1gram-20120701-2.gz
wget -nc http://storage.googleapis.com/books/ngrams/books/googlebooks-eng-all-1gram-20120701-3.gz
wget -nc http://storage.googleapis.com/books/ngrams/books/googlebooks-eng-all-1gram-20120701-4.gz
wget -nc http://storage.googleapis.com/books/ngrams/books/googlebooks-eng-all-1gram-20120701-5.gz
wget -nc http://storage.googleapis.com/books/ngrams/books/googlebooks-eng-all-1gram-20120701-6.gz
wget -nc http://storage.googleapis.com/books/ngrams/books/googlebooks-eng-all-1gram-20120701-7.gz
wget -nc http://storage.googleapis.com/books/ngrams/books/googlebooks-eng-all-1gram-20120701-8.gz
wget -nc http://storage.googleapis.com/books/ngrams/books/googlebooks-eng-all-1gram-20120701-9.gz
wget -nc http://storage.googleapis.com/books/ngrams/books/googlebooks-eng-all-1gram-20120701-a.gz
wget -nc http://storage.googleapis.com/books/ngrams/books/googlebooks-eng-all-1gram-20120701-b.gz
wget -nc http://storage.googleapis.com/books/ngrams/books/googlebooks-eng-all-1gram-20120701-c.gz
wget -nc http://storage.googleapis.com/books/ngrams/books/googlebooks-eng-all-1gram-20120701-d.gz
wget -nc http://storage.googleapis.com/books/ngrams/books/googlebooks-eng-all-1gram-20120701-e.gz
wget -nc http://storage.googleapis.com/books/ngrams/books/googlebooks-eng-all-1gram-20120701-f.gz
wget -nc http://storage.googleapis.com/books/ngrams/books/googlebooks-eng-all-1gram-20120701-g.gz
wget -nc http://storage.googleapis.com/books/ngrams/books/googlebooks-eng-all-1gram-20120701-h.gz
wget -nc http://storage.googleapis.com/books/ngrams/books/googlebooks-eng-all-1gram-20120701-i.gz
wget -nc http://storage.googleapis.com/books/ngrams/books/googlebooks-eng-all-1gram-20120701-j.gz
wget -nc http://storage.googleapis.com/books/ngrams/books/googlebooks-eng-all-1gram-20120701-k.gz
wget -nc http://storage.googleapis.com/books/ngrams/books/googlebooks-eng-all-1gram-20120701-l.gz
wget -nc http://storage.googleapis.com/books/ngrams/books/googlebooks-eng-all-1gram-20120701-m.gz
wget -nc http://storage.googleapis.com/books/ngrams/books/googlebooks-eng-all-1gram-20120701-n.gz
wget -nc http://storage.googleapis.com/books/ngrams/books/googlebooks-eng-all-1gram-20120701-o.gz
wget -nc http://storage.googleapis.com/books/ngrams/books/googlebooks-eng-all-1gram-20120701-p.gz
wget -nc http://storage.googleapis.com/books/ngrams/books/googlebooks-eng-all-1gram-20120701-q.gz
wget -nc http://storage.googleapis.com/books/ngrams/books/googlebooks-eng-all-1gram-20120701-r.gz
wget -nc http://storage.googleapis.com/books/ngrams/books/googlebooks-eng-all-1gram-20120701-s.gz
wget -nc http://storage.googleapis.com/books/ngrams/books/googlebooks-eng-all-1gram-20120701-t.gz
wget -nc http://storage.googleapis.com/books/ngrams/books/googlebooks-eng-all-1gram-20120701-u.gz
wget -nc http://storage.googleapis.com/books/ngrams/books/googlebooks-eng-all-1gram-20120701-v.gz
wget -nc http://storage.googleapis.com/books/ngrams/books/googlebooks-eng-all-1gram-20120701-w.gz
wget -nc http://storage.googleapis.com/books/ngrams/books/googlebooks-eng-all-1gram-20120701-x.gz
wget -nc http://storage.googleapis.com/books/ngrams/books/googlebooks-eng-all-1gram-20120701-y.gz
wget -nc http://storage.googleapis.com/books/ngrams/books/googlebooks-eng-all-1gram-20120701-z.gz
wget -nc http://storage.googleapis.com/books/ngrams/books/googlebooks-eng-all-1gram-20120701-other.gz
wget -nc http://storage.googleapis.com/books/ngrams/books/googlebooks-eng-all-1gram-20120701-pos.gz
wget -nc http://storage.googleapis.com/books/ngrams/books/googlebooks-eng-all-1gram-20120701-punctuation.gz
